services:
  webservice:
    build: webservice
    ports:
      - "2000:2000"
    image: webservice
    container_name: webservice
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    image: frontend
    container_name: frontend